-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 09:50:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(50) NOT NULL,
  `nome_fantasia` VARCHAR(50) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `telefone` CHAR(11) NULL,
  `senha` VARCHAR(30) NOT NULL,
  `status_usuario` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `sigla` CHAR(2) NOT NULL,
  `nome_estado` VARCHAR(50) NOT NULL,
  `regiao` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_estado`),
  CONSTRAINT chkRegiao CHECK (`regiao` IN ('Norte', 'Nordeste', 'Centro-Oeste', 'Sudeste', 'Sul')),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE,
  UNIQUE INDEX `nome_estado_UNIQUE` (`nome_estado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` CHAR(8) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(100) NULL,
  `municipio` VARCHAR(50) NOT NULL,
  `fk_estado` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_estado1_idx` (`fk_estado` ASC) VISIBLE,
  INDEX `fk_endereco_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_estado1`
    FOREIGN KEY (`fk_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`galpao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`galpao` (
  `id_galpao` INT NOT NULL AUTO_INCREMENT,
  `nome_galpao` VARCHAR(50) NOT NULL,
  `ala` CHAR(2) NULL,
  `fk_endereco` INT NOT NULL,
  PRIMARY KEY (`id_galpao`),
  INDEX `fk_galpao_endereco1_idx` (`fk_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_galpao_endereco1`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `mydb`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tanque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tanque` (
  `id_tanque` INT NOT NULL AUTO_INCREMENT,
  `capacidade` DECIMAL(10,2) NOT NULL,
  `fk_galpao` INT NOT NULL,
  PRIMARY KEY (`id_tanque`),
  INDEX `fk_tanque_galpao1_idx` (`fk_galpao` ASC) VISIBLE,
  CONSTRAINT `fk_tanque_galpao1`
    FOREIGN KEY (`fk_galpao`)
    REFERENCES `mydb`.`galpao` (`id_galpao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor_temperatura_umidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor_temperatura_umidade` (
  `id_sensor` INT NOT NULL AUTO_INCREMENT,
  `data_instalacao` DATE NOT NULL,
  `status_sensor` TINYINT(1) NOT NULL,
  `temperatura_max` DECIMAL(10,2) NOT NULL,
  `temperatura_min` DECIMAL(10,2) NOT NULL,
  `umidade_max` DECIMAL(10,2) NOT NULL,
  `umidade_min` DECIMAL(10,2) NOT NULL,
  `fk_tanque` INT NOT NULL,
  PRIMARY KEY (`id_sensor`),
  INDEX `fk_sensor_temperatura_umidade_tanque1_idx` (`fk_tanque` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_temperatura_umidade_tanque1`
    FOREIGN KEY (`fk_tanque`)
    REFERENCES `mydb`.`tanque` (`id_tanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leitura_sensor_temperatura_umidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leitura_sensor_temperatura_umidade` (
  `id_leitura` INT NOT NULL AUTO_INCREMENT,
  `historico_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `temperatura` DECIMAL(10,2) NOT NULL,
  `umidade` DECIMAL(10,2) NOT NULL,
  `fk_sensor_temperatura_umidade` INT NOT NULL,
  `status_tanque` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_leitura`),
  INDEX `fk_leitura_sensor_temperatura_umidade_sensor_temperatura_um_idx` (`fk_sensor_temperatura_umidade` ASC) VISIBLE,
  CONSTRAINT `fk_leitura_sensor_temperatura_umidade_sensor_temperatura_umid1`
    FOREIGN KEY (`fk_sensor_temperatura_umidade`)
    REFERENCES `mydb`.`sensor_temperatura_umidade` (`id_sensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
